#!/usr/bin/python3
# The code write by (Mr.nope)
import os
import time
# color
class color:
    green = '\033[92m'
    red = '\033[91m'
    white = '\033[0m'
    blue = '\033[96m'
# code
os.system("clear")
time.sleep(2)
print(color.green + """


:'######:::::'###::::'##::::'##::::'##::::'##::::'###:::::'######::'##:::'##:'########:'########:::'######::
'##... ##:::'## ##::: ###::'###:::: ##:::: ##:::'## ##:::'##... ##: ##::'##:: ##.....:: ##.... ##:'##... ##:
 ##:::..:::'##:. ##:: ####'####:::: ##:::: ##::'##:. ##:: ##:::..:: ##:'##::: ##::::::: ##:::: ##: ##:::..::
 ##:::::::'##:::. ##: ## ### ##:::: #########:'##:::. ##: ##::::::: #####:::: ######::: ########::. ######::
 ##::::::: #########: ##. #: ##:::: ##.... ##: #########: ##::::::: ##. ##::: ##...:::: ##.. ##::::..... ##:
 ##::: ##: ##.... ##: ##:.:: ##:::: ##:::: ##: ##.... ##: ##::: ##: ##:. ##:: ##::::::: ##::. ##::'##::: ##:
. ######:: ##:::: ##: ##:::: ##:::: ##:::: ##: ##:::: ##:. ######:: ##::. ##: ########: ##:::. ##:. ######::
:......:::..:::::..::..:::::..:::::..:::::..::..:::::..:::......:::..::::..::........::..:::::..:::......:::
""" + color.red)
print(color.red + "\t{1}." + color.blue + "start hacking" ,color.red + "\t{2}." + color.blue + "United Status")
print(color.red + "\t{3}." + color.blue + "Germany" ,color.red + "\t \t{4}." + color.blue + "Turkey" + color.white)
print(color.red + "\t{5}." + color.blue + "Spain" ,color.red + "\t \t{6}." + color.blue + "Canada" + color.white)
print(color.red + "\t{7}." + color.blue + "chine" ,color.red + "\t \t{8}." + color.blue + "Brazil" + color.white)
print(color.red + "\t{9}." + color.blue + "India" ,color.red + "\t \t{10}." + color.blue + "Iran" + color.white)
print(color.red + "\t{11}." + color.green + "Exit")
choose = str(input(color.green + "\ncam/Hackers/> " + color.white))
if(str(choose) == '2'):
  os.system("clear")
  time.sleep(1)                                                            
  print(color.green + "http://23.30.43.54:80") 	
  time.sleep(1)                                                                          
  print(color.green + "http://128.252.105.1:80")                                                                         
  time.sleep(1)
  print(color.green + "http://152.33.35.54:80")                                                                         
  time.sleep(1)
  print(color.green + "http://192.251.46.39:80") 
  time.sleep(1)                                                                          
  print(color.green + "http://192.135.76.230:80")                                                                          
  time.sleep(1)
  print(color.green + "http://204.128.145.121:80")                                                                        
  time.sleep(1)
  print(color.green + "http://98.189.75.103:8090")                                                                       
  time.sleep(1)
  print(color.green + "http://98.255.34.120:80")                                                                          
  time.sleep(1)
  print(color.green + "http://98.32.159.121:8084")                                                                         
  time.sleep(1)
  print(color.green + "http://209.193.10.120:8080")                                                                       
  time.sleep(1)
  print(color.green + "http://75.45.217.119:8081")                                                                      
  time.sleep(1) 
  print(color.green + "http://67.184.163.123:8080")                                                                       
  time.sleep(1)
  print(color.green + "http://172.112.184.123:8082")                                                                      
  time.sleep(1)
  print(color.green + "http://184.56.99.102:8888")                                                                     
  time.sleep(1)
  print(color.green + "http://69.39.111.111:8888")                                                                       
  time.sleep(1)
  print(color.green + "http://166.141.236.121:81")                                                                       
  time.sleep(1)
  print(color.green + "http://65.140.81.102:80")                                                                       
  time.sleep(1)
  print(color.green + "http://12.31.214.118:80")
  time.sleep(2)
  try1 = str(input("press Enter... "))
  if(str(try1) == ''):
    os.system("python3 camhackers.py")
  else:
      os.system("python3 camhackers.py")
elif(str(choose) == '3'):
    os.system("clear")
    time.sleep(1)
    print(color.green + "http://149.220.61.172:80")                                                                         
    time.sleep(1)  
    print(color.green + "http://217.91.208.210:80")                                                                        
    time.sleep(1)
    print(color.green + "http://213.214.16.220:8080")                                                                        
    time.sleep(1)
    print(color.green + "http://80.149.251.53:8080")                                                                      
    time.sleep(1)
    print(color.green + "http://93.199.249.139:82")                                                                       
    time.sleep(1)
    print(color.green + "http://93.199.249.139:83") 
    time.sleep(1)
    print(color.green + "http://93.209.250.117:8090")                                                                        
    time.sleep(1)
    print(color.green + "http://217.95.27.131:80")                                                                      
    time.sleep(1)
    print(color.green + "http://138.245.35.119:8888")                                                                        
    time.sleep(1)
    print(color.green + "http://87.143.96.126:50000") 
    time.sleep(1)
    print(color.green + "http://185.113.7.142:9000")                                                                      
    time.sleep(1)
    print(color.green + "http://87.167.219.131:8080")                                                                       
    time.sleep(1)
    print(color.green + "http://79.193.202.139:80")                                                                      
    time.sleep(1)
    print(color.green + "http://79.253.201.130:91")                                                                        
    time.sleep(1)
    print(color.green + "http://89.0.230.143:8082")                                                                         
    time.sleep(1)
    print(color.green + "http://79.212.67.127:81" + color.white)
    try2 = str(input("press Enter... "))
    if(str(try2) == ''):
      os.system("python3 camhackers.py")
    else:
        os.system("python3 camhackers.py")
elif(str(choose) == '4'):
    os.system("clear")
    time.sleep(2)
    print(color.green + "http://88.249.25.35:60001")                                                                         
    time.sleep(1)  
    print(color.green + "http://85.98.30.29:60001")                                                                          
    time.sleep(1)
    print(color.green + "http://81.214.140.215:60001")                                                                       
    time.sleep(1)
    print(color.green + "http://85.104.100.184:8000")                                                                        
    time.sleep(1)
    print(color.green + "http://81.213.157.86:90")                                                                           
    time.sleep(1)
    print(color.green + "http://213.153.251.166:85")                                                                        
    time.sleep(1)
    print(color.green + "http://88.247.127.5:6001")                                                                         
    time.sleep(1)
    print(color.green + "http://212.15.30.185:81")                                                                        
    time.sleep(1)
    print(color.green + "http://78.186.1.99:60001")                                                                      
    time.sleep(1)
    print(color.green + "http://88.247.100.83:60001")                                                                       
    time.sleep(1)
    print(color.green + "http://85.96.181.82:50001")                                                                        
    time.sleep(1)
    print(color.green + "http://31.223.12.40:1024")                                                                          
    time.sleep(1)
    print(color.green + "http://95.9.96.3:91")                                                                      
    time.sleep(1)
    print(color.green + "http://88.249.31.191:60001")                                                                      
    time.sleep(1)
    print(color.green + "http://81.215.198.177:8082")                                                                        
    time.sleep(1)
    print(color.green + "http://78.186.7.161:8001")                                                                       
    time.sleep(1)
    print(color.green + "http://95.9.143.108:60001")                                                                       
    time.sleep(1)
    print(color.green + "http://85.99.124.57:60001")                                                                      
    time.sleep(1)
    print(color.green + "http://78.187.174.16:60001")                                                                        
    time.sleep(1)
    print(color.green + "http://85.99.96.3:60001")                                                                     
    time.sleep(1)
    print(color.green + "http://88.247.186.171:60001")                                                                       
    time.sleep(1)
    print(color.green + "http://85.97.190.82:60001")                                                                        
    time.sleep(1)
    print(color.green + "http://78.187.224.75:60001")                                                                      
    time.sleep(1)
    print(color.green + "http://92.44.191.187:60001")                                                                        
    time.sleep(1)
    print(color.green + "http://212.154.88.129:60001")                                                                       
    time.sleep(1)
    print(color.green + "http://95.9.152.108:86")                                                                     
    time.sleep(1)
    print(color.green + "http://85.105.204.100:60001")                                                                      
    time.sleep(1)
    print(color.green + "http://78.189.179.82:60001" + color.white)
    time.sleep(2)
    try4 = str(input("press Enter... "))
    if(str(try4) == ''):
      os.system("python3 camhackers.py")
    else:
        os.system("python3 camhackers.py")
elif(str(choose) == '5'):
    os.system("clear")
    time.sleep(2)
    print(color.green + "http://212.142.228.68:80") 
    time.sleep(1)                                                                       
    print(color.green + "http://79.157.187.154:80")                                                                         
    time.sleep(1)
    print(color.green + "http://85.50.248.145:83")                                                                         
    time.sleep(1)
    print(color.green + "http://80.39.179.146:80")                                                                     
    time.sleep(1)
    print(color.green + "http://185.191.43.144:60001")                                                                      
    time.sleep(1)
    print(color.green + "http://37.133.124.140:8080")                                                                        
    time.sleep(1)
    print(color.green + "http://46.26.42.148:85")                                                                         
    time.sleep(1)
    print(color.green + "http://85.136.99.142:90")                                                                           
    time.sleep(1)
    print(color.green + "http://88.22.65.145:91")                                                                            
    time.sleep(1)
    print(color.green + "http://83.33.93.123:8001")                                                                          
    time.sleep(1)
    print(color.green + "http://79.156.187.103:8082")                                                                       
    time.sleep(1)
    print(color.green + "http://79.148.95.123:8001")                                                                         
    time.sleep(1)
    print(color.green + "http://2.136.203.133:80")                                                                      
    time.sleep(1)
    print(color.green + "http://37.10.179.143:81")                                                                      
    time.sleep(1)
    print(color.green + "http://185.86.212.131:8200")                                                                     
    time.sleep(1)
    print(color.green + "http://185.86.212.131:60001")                                                                      
    time.sleep(1)
    print(color.green + "http://31.210.228.122:8080")                                                                     
    time.sleep(1)
    print(color.green + "http://185.239.39.102:8080")                                                                        
    time.sleep(1)
    print(color.green + "http://212.170.194.121:8001")                                                                       
    time.sleep(1)
    print(color.green + "http://81.36.211.110:80")                                                                         
    time.sleep(1)
    print(color.green + "http://2.136.215.110:81")                                                                           
    time.sleep(1)
    print(color.green + "http://185.159.115.76:8081")                                                                        
    time.sleep(1)
    print(color.green + "http://194.13.85.74:8081")                                                                         
    time.sleep(1)
    print(color.green + "http://157.97.190.96:80")                                                                           
    time.sleep(1)
    print(color.green + "http://83.36.30.94:83" + color.white)
    time.sleep(2)
    try6 = str(input("press Enter... "))
    if(str(try6) == ''):
      os.system("python3 camhakers.py")
    else:
        os.system("python3 camhackers.py")
elif(str(choose) == '6'):
    os.system("clear")
    time.sleep(2)
    print(color.green + "http://206.47.135.122:8001")
    time.sleep(1)                                                                        
    print(color.green + "http://184.70.14.182:80")                                                                           
    time.sleep(1)  
    print(color.green + "http://205.237.248.39:80")                                                                          
    time.sleep(1)  
    print(color.green + "http://205.206.191.150:60001")                                                                      
    time.sleep(1)  
    print(color.green + "http://70.53.193.146:60001")                                                                        
    time.sleep(1)  
    print(color.green + "http://70.29.143.141:60001")                                                                        
    time.sleep(1)  
    print(color.green + "http://72.138.221.151:60001")                                                                       
    time.sleep(1)  
    print(color.green + "http://184.146.218.144:60001")                                                                      
    time.sleep(1)  
    print(color.green + "http://148.170.137.127:80")                                                                         
    time.sleep(1)  
    print(color.green + "http://198.48.235.134:8080")                                                                        
    time.sleep(1)    
    print(color.green + "http://70.31.189.153:80")                                                                           
    time.sleep(1)  
    print(color.green + "http://207.96.205.104:85")                                                                         
    time.sleep(1)    
    print(color.green + "http://99.224.60.143:8080")                                                                         
    time.sleep(1)    
    print(color.green + "http://66.131.218.127:88")                                                                          
    time.sleep(1)  
    print(color.green + "http://207.216.10.129:60001")                                                                       
    time.sleep(1)  
    print(color.green + "http://199.255.220.140:80")                                                                         
    time.sleep(1)  
    print(color.green + "http://50.68.189.142:50001")                                                                      
    time.sleep(1)  
    print(color.green + "http://50.68.189.142:50000")                                                                       
    time.sleep(1)  
    print(color.green + "http://207.189.209.130:83")                                                                       
    time.sleep(1)  
    print(color.green + "http://162.156.255.140:81")                                                                        
    time.sleep(1)  
    print(color.green + "http://184.151.32.102:80")                                                                        
    time.sleep(1)  
    print(color.green + "http://174.90.163.121:80")                                                                      
    time.sleep(1)  
    print(color.green + "http://24.231.13.103:60001")                                                                       
    time.sleep(1)  
    print(color.green + "http://162.247.229.123:80")                                                                       
    time.sleep(1)  
    print(color.green + "http://206.162.179.102:80")                                                                         
    time.sleep(1)  
    print(color.green + "http://24.80.7.86:60001" + color.white)
    time.sleep(2)                                                                                                                                                    
    try7 = str(input("press Enter... "))
    if(str(try7) == ''):
      os.system("python3 camhackers.py")
    else:
        os.system("python3 camhackers.py")
elif(str(choose) == '7'):
    os.system("clear")
    time.sleep(2)
    print(color.green + "http://116.90.82.254:81")                                                                          
    time.sleep(1)  
    print(color.green + "http://14.18.136.74:82")                                                                            
    time.sleep(1)  
    print(color.green + "http://116.55.97.228:8000")                                                                         
    time.sleep(1)  
    print(color.green + "http://27.17.60.134:88")                                                                            
    time.sleep(1)  
    print(color.green + "http://117.175.104.143:91")                                                                         
    time.sleep(1)  
    print(color.green + "http://175.167.187.153:60001")                                                                      
    time.sleep(1)  
    print(color.green + "http://113.68.16.146:60001")                                                                        
    time.sleep(1)  
    print(color.green + "http://113.230.27.142:60001")                                                                       
    time.sleep(1)  
    print(color.green + "http://27.199.6.152:60001")                                                                         
    time.sleep(1)  
    print(color.green + "http://60.6.29.144:60001")                                                                          
    time.sleep(1)  
    print(color.green + "http://42.53.51.118:60001")                                                                         
    time.sleep(1)  
    print(color.green + "http://42.84.210.146:60001")                                                                        
    time.sleep(1)  
    print(color.green + "http://110.252.43.132:60001")                                                                     
    time.sleep(1)  
    print(color.green + "http://116.117.17.145:60001")                                                                       
    time.sleep(1)  
    print(color.green + "http://110.251.6.153:60001")                                                                        
    time.sleep(1)    
    print(color.green + "http://114.224.212.133:8001")                                                                      
    time.sleep(1)  
    print(color.green + "http://117.158.166.130:91")                                                                         
    time.sleep(1)  
    print(color.green + "http://114.232.35.126:60001")                                                                       
    time.sleep(1)  
    print(color.green + "http://60.0.224.128:60001")                                                                     
    time.sleep(1)  
    print(color.green + "http://116.115.95.128:60001")                                                                     
    time.sleep(1)  
    print(color.green + "http://171.107.75.123:60001")                                                                    
    time.sleep(1)  
    print(color.green + "http://113.228.162.121:60001")                                                                     
    time.sleep(1)  
    print(color.green + "http://121.226.17.102:60001")                                                                       
    time.sleep(1)  
    print(color.green + "http://8.136.156.126:86")                                                                      
    time.sleep(1)  
    print(color.green + "http://175.11.21.111:60001" + color.white)
    time.sleep(2)
    try8 = str(input("press Enter... "))
    if(str(try8) == ''):
      os.system("python3 camhackers.py")
    else:
        os.system("python3 camhackers.py")
elif(str(choose) == '8'):
    os.system("clear")
    time.sleep(2)
    print(color.green + "http://152.92.155.15:80")
    time.sleep(1)                                                                                                                                               
    print(color.green + "http://201.28.98.51:80")                                                                            
    time.sleep(1)    
    print(color.green + "http://179.236.98.187:8000")                                                                        
    time.sleep(1)    
    print(color.green + "http://179.108.36.179:80")                                                                          
    time.sleep(1)    
    print(color.green + "http://201.77.130.198:80")                                                                          
    time.sleep(1)    
    print(color.green + "http://179.178.65.198:8082")                                                                        
    time.sleep(1)    
    print(color.green + "http://189.106.127.182:80")                                                                         
    time.sleep(1)    
    print(color.green + "http://201.77.130.139:8000")                                                                       
    time.sleep(1)    
    print(color.green + "http://177.22.182.180:8080")                                                                        
    time.sleep(1)    
    print(color.green + "http://177.85.178.180:8083")                                                                       
    time.sleep(1)    
    print(color.green + "http://179.190.123.186:8081")                                                                      
    time.sleep(1)    
    print(color.green + "http://189.4.107.186:60001")                                                                     
    time.sleep(1)    
    print(color.green + "http://177.81.117.139:60001")                                                                       
    time.sleep(1)    
    print(color.green + "http://191.35.102.181:60001")                                                                     
    time.sleep(1)    
    print(color.green + "http://191.13.107.193:60001")                                                                       
    time.sleep(1)    
    print(color.green + "http://179.211.193.168:60001")                                                                      
    time.sleep(1)    
    print(color.green + "http://179.108.34.187:80")                                                                          
    time.sleep(1)    
    print(color.green + "http://179.108.36.173:80")                                                                          
    time.sleep(1)    
    print(color.green + "http://190.107.91.166:8080")                                                                        
    time.sleep(1)    
    print(color.green + "http://201.1.40.186:83")                                                                            
    time.sleep(1)    
    print(color.green + "http://189.126.226.180:8001")                                                                       
    time.sleep(1)    
    print(color.green + "http://200.0.33.190:80")                                                                            
    time.sleep(1)    
    print(color.green + "http://189.126.226.180:8000")                                                                       
    time.sleep(1)    
    print(color.green + "http://191.35.170.158:60001")                                                                       
    time.sleep(1)    
    print(color.green + "http://191.35.170.158:80")                                                                          
    time.sleep(1)    
    print(color.green + "http://201.93.238.188:60001")                                                                       
    time.sleep(1)    
    print(color.green + "http://186.235.83.158:8090")                                                                        
    time.sleep(1)    
    print(color.green + "http://186.235.83.158:8084")                                                                        
    time.sleep(1)    
    print(color.green + "http://186.235.83.158:8082")                                                                        
    time.sleep(1)    
    print(color.green + "http://192.12.114.147:8081")                                                                        
    time.sleep(1)    
    print(color.green + "http://191.185.221.165:5000" + color.white)                                                                 
    time.sleep(2)
    try9 = str(input("press Enter... "))
    if(str(try9) == ''):
      os.system("python3 camhackers.py")
    else:
        os.system("python3 camhackers.py")
elif(str(choose) == '9'):
    os.system("clear")
    time.sleep(2)
    print(color.green + "http://78.26.13.12:80")
    time.sleep(1)                                                                             
    print(color.green + "http://80.213.101.181:60001")
    time.sleep(1)                                                                       
    print(color.green + "http://89.11.212.189:8080")                                                                         
    time.sleep(1) 
    print(color.green + "http://37.253.162.180:8001")                                                                        
    time.sleep(1) 
    print(color.green + "http://37.253.161.185:8001")                                                                        
    time.sleep(1) 
    print(color.green + "http://185.83.16.172:80")                                                                           
    time.sleep(1) 
    print(color.green + "http://88.91.87.168:8080")                                                                          
    time.sleep(1) 
    print(color.green + "http://88.90.43.189:9000")                                                                          
    time.sleep(1) 
    print(color.green + "http://88.91.87.168:8081")                                                                          
    time.sleep(1) 
    print(color.green + "http://185.193.94.146:80")                                                                          
    time.sleep(1) 
    print(color.green + "http://185.193.94.146:60001")                                                                       
    time.sleep(1) 
    print(color.green + "http://85.93.226.157:8081")                                                                         
    time.sleep(1) 
    print(color.green + "http://85.93.226.157:8082")                                                                         
    time.sleep(1) 
    print(color.green + "http://85.93.226.157:8083")                                                                         
    time.sleep(1) 
    print(color.green + "http://92.220.68.140:81")                                                                           
    time.sleep(1) 
    print(color.green + "http://109.247.68.134:81")                                                                          
    time.sleep(1) 
    print(color.green + "http://89.162.116.143:80")                                                                          
    time.sleep(1) 
    print(color.green + "http://185.143.217.131:81")                                                                         
    time.sleep(1) 
    print(color.green + "http://185.143.217.131:82")                                                                         
    time.sleep(1) 
    print(color.green + "http://88.88.205.127:60001")                                                                        
    time.sleep(1) 
    print(color.green + "http://195.139.157.109:8082")                                                                       
    time.sleep(1) 
    print(color.green + "http://51.174.114.102:8090")                                                                        
    time.sleep(1) 
    print(color.green + "http://185.155.215.110:80")                                                                         
    time.sleep(1) 
    print(color.green + "http://89.151.216.102:8081")                                                                        
    time.sleep(1) 
    print(color.green + "http://92.220.173.101:80")                                                                          
    time.sleep(1) 
    print(color.green + "http://212.125.208.96:8080")                                                                       
    time.sleep(1) 
    print(color.green + "http://79.161.111.78:8080")                                                                         
    time.sleep(1) 
    print(color.green + "http://46.9.1.2:8082")                                                                              
    time.sleep(1) 
    print(color.green + "http://91.149.48.42:80")                                                                            
    time.sleep(1) 
    print(color.green + "http://88.90.41.36:60001")                                                                          
    time.sleep(1) 
    print(color.green + "http://85.167.218.3:82")                                                                           
    time.sleep(1) 
    print(color.green + "http://62.92.105.6:8081" + color.white)
    time.sleep(2)
    try10 = str(input("press Enter... "))
    if(str(try10) == ''):
      os.system("python3 camhackers.py")
    else:
        os.system("python33 camhackers.py")
elif(str(choose) == '10'):
    os.system("clear")
    time.sleep(2)
    print(color.green + "http://83.23.108.153:80") 
    time.sleep(1)                                                                           
    print(color.green + "http://193.106.130.146:6003")                                                                       
    time.sleep(1)                                                                           
    print(color.green + "http://188.125.56.161:89")                                                                          
    time.sleep(1)                                                                           
    print(color.green + "http://213.108.119.134:80")                                                                         
    time.sleep(1)                                                                           
    print(color.green + "http://79.162.250.133:6003")                                                                        
    time.sleep(1)                                                                           
    print(color.green + "http://83.22.186.141:8080")                                                                         
    time.sleep(1)                                                                           
    print(color.green + "http://93.176.214.123:8081")                                                                        
    time.sleep(1)                                                                           
    print(color.green + "http://185.229.126.96:8082")                                                                        
    time.sleep(1)                                                                           
    print(color.green + "http://159.205.23.68:80")                                                                           
    time.sleep(1)                                                                           
    print(color.green + "http://31.6.212.70:82")                                                                             
    time.sleep(1)                                                                           
    print(color.green + "http://195.205.33.48:8080")                                                                         
    time.sleep(1)                                                                           
    print(color.green + "http://178.16.115.44:8080")                                                                         
    time.sleep(1)                                                                           
    print(color.green + "http://31.179.161.42:91")                                                                           
    time.sleep(1)                                                                           
    print(color.green + "http://46.238.103.4:80")                                                                            
    time.sleep(1)                                                                           
    print(color.green + "http://84.38.21.204:8081")                                                                          
    time.sleep(1)                                                                           
    print(color.green + "http://83.238.38.210:8080")                                                                         
    time.sleep(1)                                                                           
    print(color.green + "http://82.177.40.173:80")                                                                           
    time.sleep(1)                                                                           
    print(color.green + "http://178.183.66.173:80")                                                                          
    time.sleep(1)                                                                           
    print(color.green + "http://87.239.174.144:60001")                                                                       
    time.sleep(1)                                                                           
    print(color.green + "http://87.239.174.144:90")                                                                          
    time.sleep(1)                                                                           
    print(color.green + "http://213.156.101.117:80")                                                                         
    time.sleep(1)                                                                           
    print(color.green + "http://94.246.155.111:8080")                                                                        
    time.sleep(1)                                                                           
    print(color.green + "http://79.162.221.114:85")                                                                          
    time.sleep(1)                                                                           
    print(color.green + "http://5.185.11.45:8081")                                                                           
    time.sleep(1)                                                                           
    print(color.green + "http://94.240.17.31:60001")                                                                         
    time.sleep(1)                                                                           
    print(color.green + "http://5.185.73.15:80")                                                                             
    time.sleep(1)                                                                           
    print(color.green + "http://82.177.67.11:8888")                                                                          
    time.sleep(1)                                                                           
    print(color.green + "http://109.241.92.192:8082")                                                                        
    time.sleep(1)                                                                           
    print(color.green + "http://178.183.157.187:8084")                                                                       
    time.sleep(1)                                                                           
    print(color.green + "http://178.183.157.187:8083")                                                                       
    time.sleep(1)                                                                           
    print(color.green + "http://89.66.222.164:8081")                                                                         
    time.sleep(1)                                                                           
    print(color.green + "http://83.3.216.134:1024")                                                                          
    time.sleep(1)                                                                           
    print(color.green + "http://31.0.198.117:90")                                                                            
    time.sleep(1)                                                                           
    print(color.green + "http://31.0.198.117:91")                                                                            
    time.sleep(1)                                                                           
    print(color.green + "http://89.78.120.107:80")                                                                           
    time.sleep(1)                                                                           
    print(color.green + "http://5.185.68.90:88")                                                                             
    time.sleep(1)                                                                           
    print(color.green + "http://188.137.52.74:80")                                                                           
    time.sleep(1)                                                                           
    print(color.green + "http://176.221.105.50:81")                                                                          
    time.sleep(1)                                                                           
    print(color.green + "http://80.50.123.38:8081")                                                                          
    time.sleep(1)                                                                           
    print(color.green + "http://89.69.62.3:60001")
    time.sleep(1)                                                                                                                                                
    print(color.green + "http://77.89.82.213:85" + color.white)
    time.sleep(2)
    try11 = str(input("press Enter... "))
    if(str(try11) == ''):
      os.system("python3 camhackers.py")
    else:
        os.system("python3 camhackers.py")
elif(str(choose) == ''):
    os.system("python3 camhackers.py")
elif(str(choose) == '1'):
    time.sleep(1)
    os.system("clear")
    time.sleep(1)
    print("""
This code write by (ms.nope)
-------[
        click the country in the selections menu and copy 
        on one of the links and retrun to the menu section 
        and click on option 1 and enter the link ]---------
        """)
    link = str(input("Enter ip or link: "))
    time.sleep(2)
    os.system("firefox " + link)
    time.sleep(2)
    try13 = str(input("Do you want to go back to menu? [y/n] "))
    if(str(try13) == 'y'):
      os.system("python3 camhackers.py")
    elif(str(try13) == 'n'):
        time.sleep(1)
        os.system("clear")
        time.sleep(1)
        print("good bye")
        exit(1)
elif(str(choose) == '11'):
    time.sleep(1)
    os.system("clear")
    time.sleep(1)
    print("good bye")
    exit(1)
elif(str(choose) == ' '):
    os.system("python3 camhackers.py")
else:
    os.system("clear")
    time.sleep(2)
    print(color.red + "Error 532 !" + color.white)
    try12 = str(input("press Enter... "))
    if(str(try12) == ''):
      os.system("python3 camhackers.py")
    else:
        os.system("python3 camhackers.py")
# cam-Hackers
